### ISSUE TITLE
Allow `| head` commands from terminal

### ISSUE THREAD

**Issue by KatrionaGoldmann** [alan-turing-institute/whatwhat#107]
Using `whatwhat person ... | head` returns an error: 
```
Fatal error: exception Sys_error("Broken pipe")
```

Suspected cause is due to broken pipe signal (see [SO question](https://stackoverflow.com/questions/22137535/ocaml-fatal-error-exception-sys-errorbroken-pipe-when-using-head-on-o))

We probably want to catch this exception and ignore the error

**Comment by yongrenjie** [comment]
Digging into this more deeply, you can't even catch the exception and call `exit`, because [`exit` causes stdout/stderr to be flushed](https://v2.ocaml.org/api/Stdlib.html#VALexit) and _this_ flushing triggers the broken pipe error again.

The `opam` tool has handled this before: https://github.com/ocaml/opam/issues/4216

And the associated PR is probably a good reference of how to fix it: https://github.com/ocaml/opam/pull/4901
